export const GET_GISTS_START = '@gists/GET_GISTS_START';
export const GET_GISTS_SUCCESS = '@gists/GET_GISTS_SUCCESS';
export const GET_GISTS_ERROR = '@gists/GET_GISTS_ERROR';

export const START_SEARCH_GISTS_BY_NAME = '@gists/SEARCH_GISTS_BY_NAME';
export const SUCCESS_SEARCH_GIST_BY_NAME = '@gists/SUCCESS_SEARCH_GIST_BY_NAME';
export const ERROR_SEARCH_GISTS_BY_NAME = '@gists/ERROR_SEARCH_GISTS_BY_NAME';